/*
 * bro static atoms
 *
 * Property names bro's native bindings use often enough that interning them
 * per call is measurable. JS_GetPropertyStr()/JS_SetPropertyStr() hash the
 * C string, probe the atom table and refcount the result on EVERY call; a
 * profile of demos/ai-arena attributed ~10,000 of those per frame to four
 * literals ("x", "z", "hw", "hd") re-parsed out of an obstacle array that
 * never changes.
 *
 * Listing a name here makes it a predefined atom, created once when the
 * runtime is built and identical in every runtime, so JS_BRO(x) is a load
 * from a constant table with no hashing and no refcounting (predefined
 * atoms are const — JS_DupAtom/JS_FreeAtom are no-ops on them).
 *
 * Two macros, because some names QuickJS already predefines:
 *   BRO_ATOM_NEW(id, str) — a new atom, appended to the predefined table
 *   BRO_ATOM_SHARED(id)   — reuses the existing JS_ATOM_<id>
 *
 * Adding a name is free at runtime but costs one atom-table slot, so keep
 * this to names that appear in a hot path. New entries go at the END of
 * their section: JS_BRO_ATOM_* indices are positional.
 */

#ifdef BRO_ATOM_NEW
BRO_ATOM_NEW(x, "x")
BRO_ATOM_NEW(y, "y")
BRO_ATOM_NEW(z, "z")
BRO_ATOM_NEW(hw, "hw")
BRO_ATOM_NEW(hd, "hd")
BRO_ATOM_NEW(color, "color")
BRO_ATOM_NEW(scale, "scale")
BRO_ATOM_NEW(yaw, "yaw")
BRO_ATOM_NEW(yOffset, "yOffset")
BRO_ATOM_NEW(offsetX, "offsetX")
BRO_ATOM_NEW(offsetZ, "offsetZ")
BRO_ATOM_NEW(variant, "variant")
BRO_ATOM_NEW(vx, "vx")
BRO_ATOM_NEW(vy, "vy")
BRO_ATOM_NEW(vz, "vz")
BRO_ATOM_NEW(teamId, "teamId")
BRO_ATOM_NEW(alive, "alive")
BRO_ATOM_NEW(speed, "speed")
BRO_ATOM_NEW(damage, "damage")
BRO_ATOM_NEW(id, "id")
BRO_ATOM_NEW(type, "type")
BRO_ATOM_NEW(radius, "radius")
BRO_ATOM_NEW(bro, "bro")
BRO_ATOM_NEW(width, "width")
BRO_ATOM_NEW(height, "height")
BRO_ATOM_NEW(data, "data")
BRO_ATOM_NEW(onError, "onError")
BRO_ATOM_NEW(onReady, "onReady")
BRO_ATOM_NEW(onDone, "onDone")
BRO_ATOM_NEW(cancelled, "cancelled")
BRO_ATOM_NEW(enabled, "enabled")
BRO_ATOM_NEW(seed, "seed")
BRO_ATOM_NEW(samples, "samples")
BRO_ATOM_NEW(sampleRate, "sampleRate")
BRO_ATOM_NEW(__bro_elem_map, "__bro_elem_map")
BRO_ATOM_NEW(position, "position")
BRO_ATOM_NEW(start, "start")
BRO_ATOM_NEW(onToken, "onToken")
BRO_ATOM_NEW(init, "init")
BRO_ATOM_NEW(image, "image")
BRO_ATOM_NEW(mode, "mode")
BRO_ATOM_NEW(end, "end")
BRO_ATOM_NEW(channels, "channels")
BRO_ATOM_NEW(stages, "stages")
BRO_ATOM_NEW(rotation, "rotation")
BRO_ATOM_NEW(frames, "frames")
BRO_ATOM_NEW(kind, "kind")
BRO_ATOM_NEW(frequency, "frequency")
BRO_ATOM_NEW(device, "device")
BRO_ATOM_NEW(depth, "depth")
BRO_ATOM_NEW(w, "w")
BRO_ATOM_NEW(stats, "stats")
BRO_ATOM_NEW(shape, "shape")
BRO_ATOM_NEW(point, "point")
BRO_ATOM_NEW(normal, "normal")
BRO_ATOM_NEW(mass, "mass")
BRO_ATOM_NEW(loop, "loop")
BRO_ATOM_NEW(hp, "hp")
BRO_ATOM_NEW(gain, "gain")
BRO_ATOM_NEW(b, "b")
BRO_ATOM_NEW(a, "a")
BRO_ATOM_NEW(_text, "_text")
BRO_ATOM_NEW(_prevented, "_prevented")
BRO_ATOM_NEW(__agents, "__agents")
BRO_ATOM_NEW(segments, "segments")
BRO_ATOM_NEW(rows, "rows")
BRO_ATOM_NEW(rate, "rate")
BRO_ATOM_NEW(r, "r")
BRO_ATOM_NEW(positions, "positions")
BRO_ATOM_NEW(parent, "parent")
BRO_ATOM_NEW(min, "min")
BRO_ATOM_NEW(max, "max")
BRO_ATOM_NEW(layers, "layers")
BRO_ATOM_NEW(g, "g")
BRO_ATOM_NEW(cellSize, "cellSize")
BRO_ATOM_NEW(__net, "__net")
BRO_ATOM_NEW(tokenizer, "tokenizer")
BRO_ATOM_NEW(relatedTarget, "relatedTarget")
BRO_ATOM_NEW(path, "path")
BRO_ATOM_NEW(origin, "origin")
BRO_ATOM_NEW(model, "model")
BRO_ATOM_NEW(maxHp, "maxHp")
BRO_ATOM_NEW(mask, "mask")
BRO_ATOM_NEW(load, "load")
BRO_ATOM_NEW(layer, "layer")
BRO_ATOM_NEW(intensity, "intensity")
BRO_ATOM_NEW(distance, "distance")
BRO_ATOM_NEW(capture, "capture")
BRO_ATOM_NEW(available, "available")
BRO_ATOM_NEW(_stopped, "_stopped")
BRO_ATOM_NEW(weight, "weight")
BRO_ATOM_NEW(userData, "userData")
BRO_ATOM_NEW(trace, "trace")
BRO_ATOM_NEW(to, "to")
BRO_ATOM_NEW(stop, "stop")
BRO_ATOM_NEW(reset, "reset")
BRO_ATOM_NEW(points, "points")
BRO_ATOM_NEW(offset, "offset")
BRO_ATOM_NEW(numFrames, "numFrames")
BRO_ATOM_NEW(linearDamping, "linearDamping")
BRO_ATOM_NEW(linear, "linear")
BRO_ATOM_NEW(language, "language")
BRO_ATOM_NEW(iterations, "iterations")
BRO_ATOM_NEW(isActive, "isActive")
BRO_ATOM_NEW(halfHeight, "halfHeight")
BRO_ATOM_NEW(friction, "friction")
BRO_ATOM_NEW(duration, "duration")
BRO_ATOM_NEW(cols, "cols")
BRO_ATOM_NEW(center, "center")
BRO_ATOM_NEW(angularDamping, "angularDamping")
BRO_ATOM_NEW(active, "active")
BRO_ATOM_NEW(xavierInit, "xavierInit")
BRO_ATOM_NEW(window, "window")
BRO_ATOM_NEW(voice, "voice")
BRO_ATOM_NEW(vigor01, "vigor01")
BRO_ATOM_NEW(twist, "twist")
BRO_ATOM_NEW(treeSize, "treeSize")
BRO_ATOM_NEW(transfer, "transfer")
BRO_ATOM_NEW(time, "time")
BRO_ATOM_NEW(targetId, "targetId")
BRO_ATOM_NEW(tanhForward, "tanhForward")
BRO_ATOM_NEW(tanhBackward, "tanhBackward")
BRO_ATOM_NEW(t, "t")
BRO_ATOM_NEW(strength, "strength")
BRO_ATOM_NEW(state, "state")
BRO_ATOM_NEW(softmaxForward, "softmaxForward")
BRO_ATOM_NEW(softmaxBackward, "softmaxBackward")
BRO_ATOM_NEW(snapshot, "snapshot")
BRO_ATOM_NEW(senescence01, "senescence01")
BRO_ATOM_NEW(samplesDelivered, "samplesDelivered")
BRO_ATOM_NEW(roughness, "roughness")
BRO_ATOM_NEW(rollingPeak, "rollingPeak")
BRO_ATOM_NEW(restitution, "restitution")
BRO_ATOM_NEW(reluForward, "reluForward")
BRO_ATOM_NEW(reluBackward, "reluBackward")
BRO_ATOM_NEW(ratio, "ratio")
BRO_ATOM_NEW(padding, "padding")
BRO_ATOM_NEW(once, "once")
BRO_ATOM_NEW(obs, "obs")
BRO_ATOM_NEW(navigator, "navigator")
BRO_ATOM_NEW(mseScalar, "mseScalar")
BRO_ATOM_NEW(moveDir, "moveDir")
BRO_ATOM_NEW(mix, "mix")
BRO_ATOM_NEW(minWeight, "minWeight")
BRO_ATOM_NEW(mesh, "mesh")
BRO_ATOM_NEW(mana, "mana")
BRO_ATOM_NEW(lossValue, "lossValue")
BRO_ATOM_NEW(lossTotal, "lossTotal")
BRO_ATOM_NEW(lossPolicy, "lossPolicy")
BRO_ATOM_NEW(location, "location")
BRO_ATOM_NEW(listen, "listen")
BRO_ATOM_NEW(linearForward, "linearForward")
BRO_ATOM_NEW(linearBackward, "linearBackward")
BRO_ATOM_NEW(lightExposure01, "lightExposure01")
BRO_ATOM_NEW(h, "h")
BRO_ATOM_NEW(gravityFactor, "gravityFactor")
BRO_ATOM_NEW(framesDelivered, "framesDelivered")
BRO_ATOM_NEW(feed, "feed")
BRO_ATOM_NEW(eps, "eps")
BRO_ATOM_NEW(elapsedMs, "elapsedMs")
BRO_ATOM_NEW(durations, "durations")
BRO_ATOM_NEW(document, "document")
BRO_ATOM_NEW(density, "density")
BRO_ATOM_NEW(damping, "damping")
BRO_ATOM_NEW(bodyId, "bodyId")
BRO_ATOM_NEW(bestVisits, "bestVisits")
BRO_ATOM_NEW(backend, "backend")
BRO_ATOM_NEW(attackSlot, "attackSlot")
BRO_ATOM_NEW(animations, "animations")
BRO_ATOM_NEW(amount, "amount")
BRO_ATOM_NEW(alphaCutoff, "alphaCutoff")
BRO_ATOM_NEW(agents, "agents")
BRO_ATOM_NEW(age01, "age01")
BRO_ATOM_NEW(addScalarInplace, "addScalarInplace")
BRO_ATOM_NEW(addInplace, "addInplace")
BRO_ATOM_NEW(abilitySlot, "abilitySlot")
BRO_ATOM_NEW(__handle, "__handle")
BRO_ATOM_NEW(__bro_node_map, "__bro_node_map")
BRO_ATOM_NEW(W, "W")
BRO_ATOM_NEW(N, "N")
BRO_ATOM_NEW(xvector, "xvector")
BRO_ATOM_NEW(visible, "visible")
BRO_ATOM_NEW(vertexCount, "vertexCount")
BRO_ATOM_NEW(version, "version")
BRO_ATOM_NEW(velocity, "velocity")
BRO_ATOM_NEW(valueTarget, "valueTarget")
BRO_ATOM_NEW(valid, "valid")
BRO_ATOM_NEW(up, "up")
BRO_ATOM_NEW(top, "top")
BRO_ATOM_NEW(timestamp, "timestamp")
BRO_ATOM_NEW(threshold, "threshold")
BRO_ATOM_NEW(texture, "texture")
BRO_ATOM_NEW(templates, "templates")
BRO_ATOM_NEW(sync, "sync")
BRO_ATOM_NEW(success, "success")
BRO_ATOM_NEW(stepIdx, "stepIdx")
BRO_ATOM_NEW(steamId, "steamId")
BRO_ATOM_NEW(skin, "skin")
BRO_ATOM_NEW(shDegree, "shDegree")
BRO_ATOM_NEW(scales, "scales")
BRO_ATOM_NEW(rz, "rz")
BRO_ATOM_NEW(ry, "ry")
BRO_ATOM_NEW(rx, "rx")
BRO_ATOM_NEW(rngSeed, "rngSeed")
BRO_ATOM_NEW(right, "right")
BRO_ATOM_NEW(resizable, "resizable")
BRO_ATOM_NEW(requireFullPath, "requireFullPath")
BRO_ATOM_NEW(recomputeNormals, "recomputeNormals")
BRO_ATOM_NEW(profileScale, "profileScale")
BRO_ATOM_NEW(preventDefault, "preventDefault")
BRO_ATOM_NEW(prefix, "prefix")
BRO_ATOM_NEW(pos, "pos")
BRO_ATOM_NEW(policyTarget, "policyTarget")
BRO_ATOM_NEW(pitchBend, "pitchBend")
BRO_ATOM_NEW(partial, "partial")
BRO_ATOM_NEW(pan, "pan")
BRO_ATOM_NEW(palette, "palette")
BRO_ATOM_NEW(open, "open")
BRO_ATOM_NEW(opacity, "opacity")
BRO_ATOM_NEW(onChunk, "onChunk")
BRO_ATOM_NEW(numGroups, "numGroups")
BRO_ATOM_NEW(now, "now")
BRO_ATOM_NEW(navGrid, "navGrid")
BRO_ATOM_NEW(names, "names")
BRO_ATOM_NEW(modulate, "modulate")
BRO_ATOM_NEW(minZ, "minZ")
BRO_ATOM_NEW(minX, "minX")
BRO_ATOM_NEW(metallic, "metallic")
BRO_ATOM_NEW(maxZ, "maxZ")
BRO_ATOM_NEW(maxX, "maxX")
BRO_ATOM_NEW(maxTorque, "maxTorque")
BRO_ATOM_NEW(maxInfluences, "maxInfluences")
BRO_ATOM_NEW(maxDistance, "maxDistance")
BRO_ATOM_NEW(margin, "margin")
BRO_ATOM_NEW(lobbyId, "lobbyId")
BRO_ATOM_NEW(levels, "levels")
BRO_ATOM_NEW(interp, "interp")
BRO_ATOM_NEW(href, "href")
BRO_ATOM_NEW(hop, "hop")
BRO_ATOM_NEW(hit, "hit")
BRO_ATOM_NEW(hero, "hero")
BRO_ATOM_NEW(heading, "heading")
BRO_ATOM_NEW(halfExtents, "halfExtents")
BRO_ATOM_NEW(gravity, "gravity")
BRO_ATOM_NEW(frameMs, "frameMs")
BRO_ATOM_NEW(frame, "frame")
BRO_ATOM_NEW(fps, "fps")
BRO_ATOM_NEW(fadeTime, "fadeTime")
BRO_ATOM_NEW(events, "events")
BRO_ATOM_NEW(eventPhase, "eventPhase")
BRO_ATOM_NEW(evaluator, "evaluator")
BRO_ATOM_NEW(elapsed, "elapsed")
BRO_ATOM_NEW(doubleSided, "doubleSided")
BRO_ATOM_NEW(dim, "dim")
BRO_ATOM_NEW(delay, "delay")
BRO_ATOM_NEW(currentTarget, "currentTarget")
BRO_ATOM_NEW(createTensor, "createTensor")
BRO_ATOM_NEW(count, "count")
BRO_ATOM_NEW(contextIds, "contextIds")
BRO_ATOM_NEW(close, "close")
BRO_ATOM_NEW(cb, "cb")
BRO_ATOM_NEW(castsShadow, "castsShadow")
BRO_ATOM_NEW(bone, "bone")
BRO_ATOM_NEW(blockMask, "blockMask")
BRO_ATOM_NEW(bestMean, "bestMean")
BRO_ATOM_NEW(axis, "axis")
BRO_ATOM_NEW(attackerId, "attackerId")
BRO_ATOM_NEW(attack, "attack")
BRO_ATOM_NEW(atlasRows, "atlasRows")
BRO_ATOM_NEW(angle, "angle")
BRO_ATOM_NEW(aimYaw, "aimYaw")
BRO_ATOM_NEW(aimPitch, "aimPitch")
BRO_ATOM_NEW(actionMask, "actionMask")
BRO_ATOM_NEW(_immediateStopped, "_immediateStopped")
BRO_ATOM_NEW(__type, "__type")
BRO_ATOM_NEW(__indexedBindings, "__indexedBindings")
BRO_ATOM_NEW(__bro_mutation_observers, "__bro_mutation_observers")
BRO_ATOM_NEW(__abilityFns, "__abilityFns")
BRO_ATOM_NEW(Hold, "Hold")
BRO_ATOM_NEW(H, "H")
BRO_ATOM_NEW(C_out, "C_out")
BRO_ATOM_NEW(C_in, "C_in")
#endif

#ifdef BRO_ATOM_SHARED
BRO_ATOM_SHARED(length)
BRO_ATOM_SHARED(name)
BRO_ATOM_SHARED(error)
BRO_ATOM_SHARED(target)
BRO_ATOM_SHARED(size)
BRO_ATOM_SHARED(value)
BRO_ATOM_SHARED(from)
BRO_ATOM_SHARED(prototype)
BRO_ATOM_SHARED(message)
BRO_ATOM_SHARED(stack)
BRO_ATOM_SHARED(source)
BRO_ATOM_SHARED(keys)
BRO_ATOM_SHARED(index)
BRO_ATOM_SHARED(done)
BRO_ATOM_SHARED(values)
#endif
